Add archive unpack task
openrelik/openrelik-worker-extraction pull request #4
Opened 2024-10-11 20:28 UTC by hacktobeer

Add archive unpack task (using 7zip) to support a wide variety of archives by default. It will take an archive file as input and create output files for each extracted file (setting source_file_id to the uuid of the input archive file).

Extra:
* debugpy added as it was missing on pyproject.toml
* queues of all tasks change to openrelik-worker-extraction

2024-10-13 18:52 UTC, berggren requested changes

2024-10-13 18:52 UTC, berggren commented on src/extract_archive.py
> +        print(f"Processing {input_file.get("path")}")
```suggestion
```

2024-10-13 18:52 UTC, berggren commented on src/extract_archive.py
> +            filename=f"archive_extract_{input_file.get("display_name")}",
```suggestion
            display_name=f"archive_extract_{input_file.get("display_name")}",
```

2024-10-13 18:52 UTC, berggren commented on src/extract_archive.py
> +                data_type="openrelik.worker.file.generic",
```suggestion
```

2024-10-13 18:52 UTC, berggren commented on src/extract_archive.py
> +                filename=file.name,
```suggestion
                display_name=file.name,
```

2024-10-14 14:33 UTC, hacktobeer commented
@berggren PTAL, small requested changes made.

2024-10-16 09:19 UTC, berggren approved these changes

2024-10-16 09:19 UTC, berggren commented on src/extract_archive.py
> +                output_path=output_path,
```suggestion
                output_path,
```

2024-10-16 09:19 UTC, berggren commented on src/extract_archive.py
> +        raise RuntimeError("archive extractor didn't create any output files")
```suggestion
        raise RuntimeError("Archive extractor didn't create any output files")
```

2024-10-16 09:30 UTC, merged